# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatToEat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatToEat
  pod "Koloda", '~> 4.3.1'
  pod "KSSwipeStack"
  
  target 'WhatToEatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhatToEatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
